package com.leo.wheel.mybatis.mapper;

import com.miaosha.dataobject.Wheel;

public interface WheelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    int insert(Wheel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    int insertSelective(Wheel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    Wheel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    int updateByPrimaryKeySelective(Wheel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    int updateByPrimaryKey(Wheel record);
}