package com.miaosha.dataobject;

import java.util.Date;

public class Wheel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel.id
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel.name
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel.status
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel.begin_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel.end_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel.id
     *
     * @return the value of wheel.id
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel.id
     *
     * @param id the value for wheel.id
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel.name
     *
     * @return the value of wheel.name
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel.name
     *
     * @param name the value for wheel.name
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel.status
     *
     * @return the value of wheel.status
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel.status
     *
     * @param status the value for wheel.status
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel.begin_date
     *
     * @return the value of wheel.begin_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel.begin_date
     *
     * @param beginDate the value for wheel.begin_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel.end_date
     *
     * @return the value of wheel.end_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel.end_date
     *
     * @param endDate the value for wheel.end_date
     *
     * @mbg.generated Tue Mar 05 11:44:05 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}